# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'HogeLabelSampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HogeLabelSampleProject
  pod 'HogeLabel', :git => 'https://github.com/takeshi-1000/HogeLabel'

  target 'HogeLabelSampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HogeLabelSampleProjectUITests' do
    # Pods for testing
  end

end